# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 304e68cafb6235218b2eeaa20a80f6af620175aacdf2c41d0fb0d0f8d44cd547e7df5a1ce5b205d6b58b497d518e0250e5ef167dd2857e18ccb74403630df30d

test:
  secret_key_base: a520bb618029a5b70c87939f7c299ed5cfc6d8432d0c2c643c10dad126a0c49d92e54c1f0195920dab27a80977a49529e64663a06d0cb10acf1ced9fa54f3727

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
